### ISSUE TITLE
Don't use relative path includes for other crates...

### ISSUE THREAD

**Issue by brandon-reinhart** [Zeenobit/moonshine_save#12]
Might be worth re-organizing your projects to not use a relative paths to each crate. This makes it hard to reproduce a dev environment to make contributions!

**Comment by Zeenobit** [comment]
I've seen other projects (such as Bevy) do this pattern:

https://github.com/bevyengine/bevy/blob/main/crates/bevy_asset/Cargo.toml
```
bevy_ecs = { path = "../bevy_ecs", version = "0.14.0-dev" }
```

This is the same pattern I copied in Moonshine. I'm not sure if there is a more correct way to do this while still allowing me to develop the larger Moonshine project locally.

I'm open to suggestions!

**Comment by Zeenobit** [comment]
Closing this in favor of #13 
Feel free to add any comments/concerns there!
