### ISSUE TITLE
May I ask what are the supported platforms?

### ISSUE THREAD

**Issue by ysypnbh** [Zeenobit/moonshine_save#15]

**Comment by Zeenobit** [comment]
This crate should be supported on all platforms which support Bevy and Rust (i.e. Windows, Linux, MacOS).

I've developed and tested the crate in Windows 11.

**Comment by ysypnbh** [comment]
> This crate should be supported on all platforms which support Bevy and Rust (i.e. Windows, Linux, MacOS).所有支持 Bevy 和 Rust 的平台（即 Windows、Linux、MacOS）都应该支持这个 crate。
> 
> I've developed and tested the crate in Windows 11.我已经在 Windows 11 中开发并测试了 crate。

Does it support web, iOS, and Android?

**Comment by Zeenobit** [comment]
It should be supported, but I haven't tested personally. Check out the official Bevy website for cross platform support:
https://bevyengine.org/
https://bevy-cheatbook.github.io/platforms.html
