### ISSUE TITLE
Save / Load on Events

### ISSUE THREAD

**Issue by data-niklas** [Zeenobit/moonshine_save#2]
Hi! Thanks for the awesome crate.

The plugins currently support loading and saving the game state dynamically using `run_if` and custom resources implementing `*FileRequest`.

I propose to use Bevy's event system, to send custom load / save events. The load / save plugins could then register event readers and load / save when they receive a new event.

https://bevy-cheatbook.github.io/programming/events.html

E.g.: repurpose `*FileRequest` to something similar to
```rust
pub struct SaveIntoFileRequest(PathBuf);
pub struct LoadFromFileRequest(PathBuf);

App::new()
        .add_event::<SaveIntoFileRequest>()
        .add_event::<LoadFromFileRequest>()
        .add_system(process_save_events)
        .add_system(process_load_events);
```

**Comment by Zeenobit** [comment]
That makes sense to me. I'll look into implementing `save_into_file_on_event<E>` and `load_from_file_on_event<E>`.

**Comment by Zeenobit** [comment]
Added in [0.2.2](https://github.com/Zeenobit/moonshine_save/releases/tag/v0.2.2)
